"""empty message

Revision ID: f2313894acfb
Revises: 9c195a7fa015
Create Date: 2025-05-08 18:27:53.252311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from src.core.services.database.postgres.models.refresh_token import NaiveDateTime


# revision identifiers, used by Alembic.
revision: str = 'f2313894acfb'
down_revision: Union[str, None] = '9c195a7fa015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', NaiveDateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('replaced_by_token', sa.String(length=255), nullable=True),
    sa.Column('created_at', NaiveDateTime(), nullable=False),
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('device_info', sa.String(length=200), nullable=True),
    sa.Column('previous_token_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['previous_token_id'], ['refresh_tokens.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
